### ISSUE TITLE
Chat Spam and lua errors

### ISSUE THREAD

**Issue by Kremdes** [funkydude/BadBoy_CCleaner#3] opened 2018-01-19 14:01 UTC
lately I get alot of lua and chat spam, I think its from either badboy or TSM, dunno for sure.

**upon login to a character I get list of these:**
18:15] BadBoy: Unexpected GUID requested by an addon: Dimino 
[18:31] BadBoy: Unexpected GUID requested by an addon:  
[14:36] BadBoy: Unexpected GUID requested by an addon:  
[14:37] BadBoy: Unexpected GUID requested by an addon:  
[14:38] BadBoy: Unexpected GUID requested by an addon:  
[14:39] BadBoy: Unexpected GUID requested by an addon:  
[14:40] BadBoy: Unexpected GUID requested by an addon:  
[14:42] BadBoy: Unexpected GUID requested by an addon:  
[14:44] BadBoy: Unexpected GUID requested by an addon:  
[14:25] BadBoy: Unexpected GUID requested by an addon: Pidela 
[14:31] BadBoy: Unexpected GUID requested by an addon: Euldoch 
[14:39] BadBoy: Unexpected GUID requested by an addon: Razuku

**e.g. lua error:**

Message: BadBoy: Unexpected GUID requested by an addon: Lorothas
Time: 01/19/18 14:51:14
Count: 1
Stack: BadBoy: Unexpected GUID requested by an addon: Lorothas
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
Interface\AddOns\BadBoy\BadBoy.lua:73: in function <Interface\AddOns\BadBoy\BadBoy.lua:68>
Interface\AddOns\BadBoy_CCleaner\BadBoy_CCleaner.lua:24: in function `filterFunc'
Interface\AddOns\ElvUI\Modules\chat\chat.lua:1172: in function `ChatFrame_MessageEventHandler'
Interface\AddOns\ElvUI\Modules\chat\chat.lua:1906: in function `DisplayChatHistory'
Interface\AddOns\ElvUI\Modules\chat\chat.lua:2289: in function `Initialize'
Interface\AddOns\ElvUI\Modules\chat\chat.lua:2383: in function <Interface\AddOns\ElvUI\Modules\chat\chat.lua:2382>
...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ore\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\core\core.lua:1371: in function `InitializeModules'
Interface\AddOns\ElvUI\core\core.lua:1550: in function `Initialize'
Interface\AddOns\ElvUI\init.lua:139: in function <Interface\AddOns\ElvUI\init.lua:138>

Locals: <none>

**Comment by funkydude** [comment] 2018-01-19 16:16
Looks like a duplicate of https://github.com/funkydude/BadBoy/issues/84

**Closed as completed by funkydude** 2018-01-19 16:16 UTC
